# Generated by Django 6.0.3 on 2026-03-29 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributetype',
            options={'ordering': ['name'], 'verbose_name': 'Attribute Type', 'verbose_name_plural': 'Attribute Types'},
        ),
        migrations.AlterModelOptions(
            name='attributevalue',
            options={'ordering': ['attribute_type', 'value'], 'verbose_name': 'Attribute Value', 'verbose_name_plural': 'Attribute Values'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='brand',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='brands', to='brands.attributevalue'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='brand',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='status',
            field=models.CharField(choices=[('Brand Evaluation', 'Brand Evaluation'), ('Negotiation', 'Negotiation'), ('Approved', 'Approved'), ('Live', 'Live')], default='Brand Evaluation', max_length=50),
        ),
        migrations.AlterField(
            model_name='brand',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['brand_name'], name='brands_bran_brand_n_be77f4_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['status'], name='brands_bran_status_92f865_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['country'], name='brands_bran_country_118a1e_idx'),
        ),
    ]
