# Generated by Django 6.0.3 on 2026-03-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_alter_attributetype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='status',
            field=models.CharField(choices=[('Brand Evaluation', 'Brand Evaluation'), ('Brand Registration', 'Brand Registration'), ('Documentation', 'Documentation'), ('Cataloguing & SKU Creation', 'Cataloguing & SKU Creation'), ('Logistics & Shipment', 'Logistics & Shipment'), ('Warehouse Handover', 'Warehouse Handover'), ('Product Live', 'Product Live')], default='Brand Evaluation', max_length=50),
        ),
    ]
