# Generated by Django 6.0.3 on 2026-03-29 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_alter_attributetype_options_and_more'),
        ('documents', '0001_initial'),
        ('workflow', '0002_alter_workflowstep_options_workflowstep_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AddField(
            model_name='document',
            name='file_name',
            field=models.CharField(default='temp', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.IntegerField(default=0, help_text='Size in bytes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('legal', 'Legal Document'), ('product_image', 'Product Image'), ('packing_list_pdf', 'Packing List PDF'), ('commercial_invoice_pdf', 'Commercial Invoice PDF'), ('bank_challan', 'Bank Challan'), ('freight_invoice', 'Freight Invoice'), ('grn', 'Goods Received Note (GRN)'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='brand_docs/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='workflow.workflowstep'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['brand', 'step'], name='documents_d_brand_i_4c4fe7_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['doc_type'], name='documents_d_doc_typ_4a1a00_idx'),
        ),
    ]
