# Generated by Django 6.0.3 on 2026-03-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_alter_attributetype_options_and_more'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowstep',
            options={'ordering': ['step_number'], 'verbose_name': 'Workflow Step', 'verbose_name_plural': 'Workflow Steps'},
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='workflowstep',
            unique_together={('brand', 'step_number')},
        ),
    ]
